### PR TITLE
Fit video to screen plugin.

### PR DESCRIPTION
**Pull request by fluzzi**
this solves issue #37, so i decide to write the plugin myself, and add it to controls. 
The plugin have 3 options, 
Cover: should resize the video keeping the aspect ratio until it fill the screen. You loose some borders.
Fill: will resize the video until it fill all the screen, this doesn't keep the aspect radio.
Default: The video will be contain by the screen without resizing.

Please give it a try and merge it.

### CODE REVIEW

**Comment by Cuevana** [comment]
We can add this button for cover zoom, but we think the fill option that doesn't keep aspect ratio is not very useful. What do you think? Maybe we can leave it out, to avoid confusing people.

**Comment by fluzzi** [comment]
Okey I think you are right, I'll change that and send a new push request

**Comment by ivantodorovich** [comment]
You don't need to send another pull request, simply update your branch.

**Comment by fluzzi** [comment]
thanks Ivan! i just update my branch and remove fill option. its ready to commit!

**Pull request merged**
