### PR TITLE
Upmix stereo to 5.1 (WARNING-- Read)

### PR DESCRIPTION
**Pull request by ivantodorovich**
One of the things that bothered me about using this App (or Popcorn) instead of downloading the torrent and playing it with VLC, is that stereo isn't upmixed to 5.1..

After a bit of research I found this page: https://code.google.com/p/chromium/issues/detail?id=355435, which talks about the same issue in Google Chrome. They recommend enabling --try-supported-channel-layouts, but warns about possible crashes.

> Sadly this feature causes crashes for many users so we had to disable it by default.

For me, it made wonders. I can finally enjoy watching movies/series in 5.1. No crash so far.
I think we should test it.. maybe the conditions that cause this to "crash for many users" aren't here.

### CODE REVIEW

**Comment by ivantodorovich** [comment]
More research: https://codereview.chromium.org/21671005

> The speculated reason is that some drivers are lying to the OS about the layouts they actually support or have broken implementations.

It **might** be possible this flag hangs someone's PC...

Maybe we should allow the user to 'enable at own risk', by passing a flag or in a settings page.

**Comment by Cuevana** [comment]
We should consider making a Preferences panel in the app, so we can try/enable optional features with more freedom and flexibility.
In this case we can avoid defining chromium-args in the main window, but we could enable/disable them in the player window when opening a new player window.

**Comment by ivantodorovich** [comment]
Is it possible to enable a chromium flag when spawning a new window?

I know there's an option to spawn a new Node Webkit instance using `new-instance`, but I don't know how will that behave.

**Comment by Cuevana** [comment]
That's something we should test. Otherwise we wouldn't be able to enable/disable this feature in-app.

**Comment by ivantodorovich** [comment]
Not without a restart. But it is a feature I would restart for.. and I know many others will to.

**Comment by Cuevana** [comment]
Sure, a restart would work. We can take that approach.

**Comment by ivantodorovich** [comment]
Ok.. so Implementation should be something like this:
[NOT TESTED]

```
function setStereoUpmix (toggle) {
  var fs = require('fs')
  var package = JSON.parse(fs.readyFileSync('package.json'))
  if (toggle) {
    package['chromium-args'] = '--try-supported-channel-layouts'
  } else {
    delete package['chromium-args']
  }
  fs.writeFileSync('package.json', JSON.stringify(package))
  // TODO: Ask the user to restar app [ YES | NO ]
}
```

But this should be in a settings page, or something.. Wouldn't know where to place it right now.

**Comment by Cuevana** [comment]
We should create a config.json file that gets read at start and sets config object from file. And every time a config attribute gets updated, we update the file.

**Comment by ivantodorovich** [comment]
I updated the branch. It now adds an options menu, visible only when `--debug`. It toggles this funcionality by editing `package.json`.

It works.. but it fails to edit the file when the app is packaged. So it won't work for release. I can't find a way to work around this..

For this to work `nodewebkit` should allow us to run a script that sets some config before launching webkit (and chromium), based on our config file/storage. It's a feature not yet implemented in `nodewebkit` (at least that I know of) and maybe it never will.

I'll close this. Maybe in future versions of `nodewebkit` this situation changes.

**Pull request closed without merging**
