### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ItsWendell**
I made some small adjustments to Cuevana Storm. I changed the torrent client max connections to 1000 and enabled DHT for much faster buffering speeds.

I also needed english subtitles for every video so I added support for OpenSubtitles.org. 

I'm just new into node.js + github so I could have made a few mistakes.

### CODE REVIEW

**Comment by ivantodorovich** [comment]
Hi @WMisiedjan 

Just a few comments. 

DHT is, by default, enabled on `peerflix`/`torrent-stream`. There's no need to explicitly set it.

Setting `connections` to more than `100` is not recommended because some routers may crash due to connection flooding. Also and more importantly, on computers with low processors it may cause video glitches on playback.

In fact, if you look at `peerflix`'s source, the default value for connections depends on the number of cores: `os.cpus().length > 1 ? 100 : 30`. In our case is even worse, because the player is running **in the same cpu core** than `peerflix`, so it doesn't matter how many cores you have. This is something I intended to fix eventually by running either `peerflix` or the player on a different process, but hadn't have time yet.

**Comment by ItsWendell** [comment]
Hmh okay, although video's are buffering far more faster for me somehow.

What do you think about the support for OpenSubtitles.org?

This is just the initial support but I want to add it proper in the near future.

I also have an idea for a trakt.tv api support for tracking movies and videos that are already seen and getting information about tv shows and movies in english.

**Comment by ivantodorovich** [comment]
It depends on your cpu, ram, etc. You might be getting better results, but it is potentially worse for others. It could be a setting, though. There's more info here: https://github.com/mafintosh/peerflix/issues/49 and https://github.com/mafintosh/peerflix/issues/18.

OpenSubtitles support looks good. :+1: Haven't tested it, though. 
I think it would be better to place it under a meplugin instead of hacking into Cuevana's core. Think of it as a player feature, similar to customSubs. You could load them asynchronously once the player starts. 
But it's just my opinion, not my call to make.

**Comment by ItsWendell** [comment]
Thanks! 
I'm here to learn and contribute so I'll look into that. 
Is there any way I can contact you directly? I have some questions about the localStorage keys.

**Comment by ivantodorovich** [comment]
I am here for the same reasons you are :)

I'm not a maintainer of Storm, @Cuevana is. I only made a few contributions because I like the project.

You can contact me by email or hangouts at: 
`console.log(['ivan', 'todorovich'].join('.')+'@'+'gmail.com')`

It would be nice to have a hangouts group or irc channel to chat about the future of this project.

**Comment by fluzzi** [comment]
Hey let me know if you need help in adding it as a me plug in, maybe I can help you with that 

It's a nice idea to use opensubtitles but I think the best approach is to join it to the actual subtitle plug in

**Comment by Cuevana** [comment]
We should implement any addition/modification to the player as a plugin, extending the core without touching it directly.
As @ivantodorovich said, 1000 open connections will be an issue for most users. A smaller 60-100 limit should be enough.

**Pull request closed without merging**
